과제 (1)

In [3]:
import gdown

gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: /content/20s_best_book.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 5.08MB/s]

'20s_best_book.json'

In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

books_df = pd.read_json('20s_best_book.json')
books = books_df.loc[:, 'no':'isbn13']
top10_books = books.head(10)
top10_books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267

In [5]:
def get_weight(isbn):
    # Yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
    # URL에 ISBN을 넣어 HTML 가져옵니다.
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser')
    # 검색 결과에서 해당 도서를 선택합니다.
    prd_info = soup.find('a', attrs={'class':'gd_name'})
    if prd_info == None:
        return ''
    # 도서 상세 페이지를 가져옵니다.
    url = 'http://www.yes24.com'+prd_info['href']
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    # 상품 상세정보 div를 선택합니다.
    prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
    # 테이블에 있는 tr 태그를 가져옵니다.
    prd_tr_list = prd_detail.find_all('tr')
    # '쪽수, 무게, 크기' 행에서 무게(g 포함 항목)를 반환합니다.
    for tr in prd_tr_list:
        if tr.find('th').get_text() == '쪽수, 무게, 크기':
            values = tr.find('td').get_text().split()
            # values 예시: ['284쪽', '|', '352g', '|', '135*208*20mm']
            for v in values:
                if 'g' in v:   # 무게: 'g'를 포함하는 항목
                    return v
    return ''

In [6]:
get_weight(9791190090018)

'496g'

In [7]:
weight = top10_books.apply(lambda row: get_weight(row['isbn13']), axis=1)
weight.name = 'weight'
print(weight)

0    496g
1    358g
2    296g
3    412g
4    388g
5    512g
6    318g
7
8    324g
9    406g
Name: weight, dtype: object

In [8]:
top10_with_weight = pd.merge(top10_books, weight,
                             left_index=True, right_index=True)
top10_with_weight

,no,ranking,bookname,authors,publisher,publication_year,isbn13,weight
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,496g
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,358g
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,296g
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,412g
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,388g
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243,512g
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005,318g
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194,
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196,324g
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630,406g

과제 (2)

In [9]:
import gdown

gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: /content/20s_best_book.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 5.05MB/s]

'20s_best_book.json'

In [10]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

books_df = pd.read_json('20s_best_book.json')
books = books_df.loc[:, 'no':'isbn13']
top10_books = books.head(10)
top10_books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267

In [11]:
# 쪽수와 무게를 동시에 추출하는 함수 (원본 get_page_cnt 확장)
def get_page_cnt(isbn):
    # Yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
    # URL에 ISBN을 넣어 HTML 가져옵니다.
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser')
    # 검색 결과에서 해당 도서를 선택합니다.
    prd_info = soup.find('a', attrs={'class':'gd_name'})
    if prd_info == None:
        return '', ''
    # 도서 상세 페이지를 가져옵니다.
    url = 'http://www.yes24.com'+prd_info['href']
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    # 상품 상세정보 div를 선택합니다.
    prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
    # 테이블에 있는 tr 태그를 가져옵니다.
    prd_tr_list = prd_detail.find_all('tr')
    # '쪽수, 무게, 크기' 행에서 쪽수와 무게를 함께 반환합니다.
    for tr in prd_tr_list:
        if tr.find('th').get_text() == '쪽수, 무게, 크기':
            values = tr.find('td').get_text().split()
            # values 예시: ['284쪽', '|', '352g', '|', '135*208*20mm']
            page = values[0]    # 쪽수: 첫 번째 항목 (예: '284쪽')
            weight = ''         # 무게 초기화
            for v in values:
                if 'g' in v:    # 무게: 'g'를 포함하는 항목 (예: '352g')
                    weight = v
                    break
            return page, weight
    return '', ''

In [12]:
get_page_cnt(9791190090018)

('344쪽', '496g')

In [13]:
page_list = []
weight_list = []

for isbn in top10_books['isbn13']:
    page, weight = get_page_cnt(isbn)
    page_list.append(page)
    weight_list.append(weight)
    print(f'ISBN {isbn}  →  쪽수: {page},  무게: {weight}')

ISBN 9791190090018  →  쪽수: 344쪽,  무게: 496g
ISBN 9791165341909  →  쪽수: 300쪽,  무게: 358g
ISBN 9791188862290  →  쪽수: 228쪽,  무게: 296g
ISBN 9788954672214  →  쪽수: 340쪽,  무게: 412g
ISBN 9788936434267  →  쪽수: 264쪽,  무게: 388g
ISBN 9788936434243  →  쪽수: 396쪽,  무게: 512g
ISBN 9791165300005  →  쪽수: 272쪽,  무게: 318g
ISBN 9788972756194  →  쪽수: ,  무게:
ISBN 9788936477196  →  쪽수: 244쪽,  무게: 324g
ISBN 9788954641630  →  쪽수: 296쪽,  무게: 406g

In [14]:
page_count = pd.Series(page_list, index=top10_books.index, name='page_count')
weight_series = pd.Series(weight_list, index=top10_books.index, name='weight')

print(page_count)
print(weight_series)

0    344쪽
1    300쪽
2    228쪽
3    340쪽
4    264쪽
5    396쪽
6    272쪽
7
8    244쪽
9    296쪽
Name: page_count, dtype: object
0    496g
1    358g
2    296g
3    412g
4    388g
5    512g
6    318g
7
8    324g
9    406g
Name: weight, dtype: object

In [16]:
result_df = pd.merge(top10_books, page_count, left_index=True, right_index=True)
result_df = pd.merge(result_df, weight_series, left_index=True, right_index=True)

result_df

,no,ranking,bookname,authors,publisher,publication_year,isbn13,page_count,weight
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,344쪽,496g
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,300쪽,358g
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,228쪽,296g
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,340쪽,412g
4,5,5,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,264쪽,388g
5,6,6,피프티 피플 :정세랑 장편소설,지은이: 정세랑,창비,2016,9788936434243,396쪽,512g
6,7,7,목소리를 드릴게요 :정세랑 소설집,지은이: 정세랑,아작,2020,9791165300005,272쪽,318g
7,8,8,나미야 잡화점의 기적 :히가시노 게이고 장편소설,지은이: 히가시노 게이고 ;옮긴이: 양윤옥,현대문학,2012,9788972756194,,
8,9,9,선량한 차별주의자,김지혜 지음,창비,2019,9788936477196,244쪽,324g
9,10,9,쇼코의 미소 :최은영 소설,지은이: 최은영,문학동네,2016,9788954641630,296쪽,406g